ACE = ../..
SRC = $(ACE)/src
COCOTB = $(ACE)/tools/cocotb
VERILOG_SOURCES = $(SRC)/hazard_ctrl.v
EXTRA_ARGS = -I$(SRC)
TOPLEVEL = hazard_ctrl
MODULE = test_hzdcontrol
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
