ACE = ../..
SRC = $(ACE)/src
COCOTB = $(ACE)/tools/cocotb
VERILOG_SOURCES = $(SRC)/mem_stage.v
TOPLEVEL = mem_stage
MODULE = test_mem_stage
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
