ACE = ../..
SRC = $(ACE)/src
COCOTB = $(ACE)/tools/cocotb
VERILOG_SOURCES = $(SRC)/regfile.v
TOPLEVEL = regfile 
MODULE = test_regfile
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
